[package]
name = "kauma-analyzer"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Christoph J. Scherr <software@cscherr.de>"]
license = "MIT"
description = "Solves exams from my professor for cryptoanalysis"
readme = "README.md"
homepage = "https://git.cscherr.de/PlexSheep/kauma"
repository = "https://git.cscherr.de/PlexSheep/kauma"


[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
